/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadejemplo.Vistas;

import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.table.DefaultTableModel;
import universidadejemplo.AccesoADatos.AlumnoData;
import universidadejemplo.AccesoADatos.InscripcionData;
import universidadejemplo.AccesoADatos.MateriaData;
import universidadejemplo.Entidades.Alumno;
import universidadejemplo.Entidades.Inscripcion;
import universidadejemplo.Entidades.Materia;

public class ManipulacionNotas extends javax.swing.JInternalFrame {

    private DefaultTableModel modelotabla = new DefaultTableModel();
    private AlumnoData alumnodata;
    private MateriaData materiadata;
    private InscripcionData inscripciondata;
    private Alumno alumno;
    private String valorNota;
    private int valorIDMat;
    private int seleccionarFila;

    public ManipulacionNotas() {
        initComponents();
        alumnodata = new AlumnoData();
        materiadata = new MateriaData();
        inscripciondata = new InscripcionData();
        cargarCombo();
        armarCabecera();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        JCBSelecAlumno = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTTablaMaterias = new javax.swing.JTable();
        JBGuardar = new javax.swing.JButton();
        JBSalir = new javax.swing.JButton();

        jLabel2.setText("Carga de Notas");

        jLabel3.setText("Seleccione un alumno:");

        JCBSelecAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBSelecAlumnoActionPerformed(evt);
            }
        });

        JTTablaMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTTablaMaterias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTTablaMateriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTTablaMaterias);

        JBGuardar.setText("Guardar");
        JBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGuardarActionPerformed(evt);
            }
        });

        JBSalir.setText("Salir");
        JBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JCBSelecAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(JBGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBSalir)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(JCBSelecAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBGuardar)
                    .addComponent(JBSalir))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSalirActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        cargarTabla();
    }//GEN-LAST:event_JBSalirActionPerformed

    private void JCBSelecAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBSelecAlumnoActionPerformed
        // TODO add your handling code here:
        cargarTabla();
    }//GEN-LAST:event_JCBSelecAlumnoActionPerformed

    private void JTTablaMateriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTTablaMateriasMouseClicked
        // TODO add your handling code here:
        seleccionarFila = JTTablaMaterias.rowAtPoint(evt.getPoint());
        valorIDMat = Integer.parseInt(JTTablaMaterias.getValueAt(seleccionarFila, 0).toString());

    }//GEN-LAST:event_JTTablaMateriasMouseClicked

    private void JBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGuardarActionPerformed
        // TODO add your handling code here:
        Alumno alumno = (Alumno) JCBSelecAlumno.getSelectedItem();
        int id = alumno.getIdAlumno();
        valorNota = (String) JTTablaMaterias.getValueAt(seleccionarFila, 2);//obtiene la nota actualizada al darle al boton guardar
        JTTablaMaterias.setValueAt(Double.parseDouble(valorNota), seleccionarFila, 2);// Actualiza la nota en la tabla
        inscripciondata.actualizarNota(Double.parseDouble(valorNota), id, valorIDMat);// Actualiza la nota en la base de datos
        cargarTabla();// Vuelve a cargar la tabla


    }//GEN-LAST:event_JBGuardarActionPerformed

    private void cargarTabla() {
        borrarFilas();
        Alumno alumno = (Alumno) JCBSelecAlumno.getSelectedItem();   // Obtiene el Alumno seleccionado en el JComboBox.
        List<Inscripcion> inscripciones = inscripciondata.obtenerInscripcionPorAlumno(alumno.getIdAlumno());    // Obtiene una lista de inscripciones del alumno.
        Set<Integer> materiasAgregadas = new HashSet<>(); // Crea un conjunto (Set) para evitar duplicados de materias.

        for (Inscripcion insc : inscripciones) { // Bucle para recorrer las inscripciones del alumno.
            Materia materia = insc.getMateria();  // Obtiene la materia asociada a la inscripción.
            if (materia != null && !materiasAgregadas.contains(materia.getIdMateria())) { // Verifica que la materia no sea nula y no se haya agregado previamente.
                // Agrega una fila a la tabla con la información de la materia y la nota.
                modelotabla.addRow(new Object[]{materia.getIdMateria(), materia.getNombre(), insc.getNota()});
                // Agrega el ID de la materia al conjunto de materias agregadas para evitar duplicados.
                materiasAgregadas.add(materia.getIdMateria());
            }
        }
    }

    private void armarCabecera() {
        modelotabla.addColumn("ID"); //Materia
        modelotabla.addColumn("Nombre"); //Materia
        modelotabla.addColumn("Nota"); //Inscripción
        JTTablaMaterias.setModel(modelotabla);
    }

    private void cargarCombo() {
        for (Alumno alumno : alumnodata.listarAlumnos()) {
            JCBSelecAlumno.addItem(alumno);
        }

    }

    private void borrarFilas() {
        ((DefaultTableModel) JTTablaMaterias.getModel()).setRowCount(0);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBGuardar;
    private javax.swing.JButton JBSalir;
    private javax.swing.JComboBox<Alumno> JCBSelecAlumno;
    private javax.swing.JTable JTTablaMaterias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
